// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: src/proto/license.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LicenseServiceClient is the client API for LicenseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LicenseServiceClient interface {
	LicenseRenew(ctx context.Context, in *LicenseRenewReq, opts ...grpc.CallOption) (*LicenseRenewRes, error)
	LicenseRefound(ctx context.Context, in *LicenseRefoundReq, opts ...grpc.CallOption) (*LicenseRefoundRes, error)
	LicensePurchase(ctx context.Context, in *LicensePurchaseReq, opts ...grpc.CallOption) (*LicensePurchaseRes, error)
}

type licenseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLicenseServiceClient(cc grpc.ClientConnInterface) LicenseServiceClient {
	return &licenseServiceClient{cc}
}

func (c *licenseServiceClient) LicenseRenew(ctx context.Context, in *LicenseRenewReq, opts ...grpc.CallOption) (*LicenseRenewRes, error) {
	out := new(LicenseRenewRes)
	err := c.cc.Invoke(ctx, "/grpc.LicenseService/LicenseRenew", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseServiceClient) LicenseRefound(ctx context.Context, in *LicenseRefoundReq, opts ...grpc.CallOption) (*LicenseRefoundRes, error) {
	out := new(LicenseRefoundRes)
	err := c.cc.Invoke(ctx, "/grpc.LicenseService/LicenseRefound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseServiceClient) LicensePurchase(ctx context.Context, in *LicensePurchaseReq, opts ...grpc.CallOption) (*LicensePurchaseRes, error) {
	out := new(LicensePurchaseRes)
	err := c.cc.Invoke(ctx, "/grpc.LicenseService/LicensePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseServiceServer is the server API for LicenseService service.
// All implementations must embed UnimplementedLicenseServiceServer
// for forward compatibility
type LicenseServiceServer interface {
	LicenseRenew(context.Context, *LicenseRenewReq) (*LicenseRenewRes, error)
	LicenseRefound(context.Context, *LicenseRefoundReq) (*LicenseRefoundRes, error)
	LicensePurchase(context.Context, *LicensePurchaseReq) (*LicensePurchaseRes, error)
	mustEmbedUnimplementedLicenseServiceServer()
}

// UnimplementedLicenseServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLicenseServiceServer struct {
}

func (UnimplementedLicenseServiceServer) LicenseRenew(context.Context, *LicenseRenewReq) (*LicenseRenewRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseRenew not implemented")
}
func (UnimplementedLicenseServiceServer) LicenseRefound(context.Context, *LicenseRefoundReq) (*LicenseRefoundRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseRefound not implemented")
}
func (UnimplementedLicenseServiceServer) LicensePurchase(context.Context, *LicensePurchaseReq) (*LicensePurchaseRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensePurchase not implemented")
}
func (UnimplementedLicenseServiceServer) mustEmbedUnimplementedLicenseServiceServer() {}

// UnsafeLicenseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LicenseServiceServer will
// result in compilation errors.
type UnsafeLicenseServiceServer interface {
	mustEmbedUnimplementedLicenseServiceServer()
}

func RegisterLicenseServiceServer(s grpc.ServiceRegistrar, srv LicenseServiceServer) {
	s.RegisterService(&LicenseService_ServiceDesc, srv)
}

func _LicenseService_LicenseRenew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseRenewReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServiceServer).LicenseRenew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LicenseService/LicenseRenew",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServiceServer).LicenseRenew(ctx, req.(*LicenseRenewReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LicenseService_LicenseRefound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseRefoundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServiceServer).LicenseRefound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LicenseService/LicenseRefound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServiceServer).LicenseRefound(ctx, req.(*LicenseRefoundReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LicenseService_LicensePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicensePurchaseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseServiceServer).LicensePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.LicenseService/LicensePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseServiceServer).LicensePurchase(ctx, req.(*LicensePurchaseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LicenseService_ServiceDesc is the grpc.ServiceDesc for LicenseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LicenseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.LicenseService",
	HandlerType: (*LicenseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LicenseRenew",
			Handler:    _LicenseService_LicenseRenew_Handler,
		},
		{
			MethodName: "LicenseRefound",
			Handler:    _LicenseService_LicenseRefound_Handler,
		},
		{
			MethodName: "LicensePurchase",
			Handler:    _LicenseService_LicensePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/proto/license.proto",
}
